// Generated by CoffeeScript 1.10.0
module.exports = function(grunt) {
  require('load-grunt-tasks')(grunt);
  grunt.initConfig({
    clean: {
      dev: ['.tmp'],
      release: ['dist']
    },
    babel: {
      options: {
        sourceMap: true
      },
      dev: {
        files: {
          '.tmp/index.js': 'src/app/index.js'
        }
      },
      release: {
        files: {
          './dist/public/app.js': './src/app/index.js',
          './dist/server.js': 'src/server/index.js'
        }
      }
    },
    watch: {
      server: {
        files: './src/app/**/*',
        tasks: ['babel:dev']
      }
    }
  });
  grunt.registerTask('default', ['clean:dev', 'babel:dev', 'watch']);
  return grunt.registerTask('release', ['clean:release', 'babel:release']);
};
